### ISSUE TITLE
Add documentation: Custom domains for project pages

### ISSUE THREAD

**Issue by beechnut** [openplans/planbox#168]
I'm looking for documentation on how to add a custom domain to a project page. When it was hosted on Heroku, we pointed a CNAME to planbox.herokuapp.com.

Once we point the CNAME (i.e. mafoodplan.org) record to the hosting URL (i.e. planbox.mapc.org), how do we configure things so that plan (i.e. planbox.mapc.org/mapc/food-plan) uses the mafoodplan.org domain?

**Comment by fkh** [comment]
After configuring the CNAME, two additional steps:

1. add the domain to the heroku application, using `heroku domain add`

2. go to */admin/custom_domains/domainmapping/*, and create a new mapping. Root path should look like this: */user/project-slug/*
